export default {
  0: {
    icon: require("../../../assets/img/game/amhg-game/recommend.png"),
    icon_active: require("../../../assets/img/game/amhg-game/recommend_active.png"),
    name: "推荐游戏"
  },
  1: {
    icon: require("../../../assets/img/game/amhg-game/hot.png"),
    icon_active: require("../../../assets/img/game/amhg-game/hot_active.png"),
    name: "热门"
  },
  2: {
    icon: require("../../../assets/img/game/new-game/jiangchi.png"),
    name: "奖池"
  },
  3: {
    icon: require("../../../assets/img/game/amhg-game/new.png"),
    icon_active: require("../../../assets/img/game/amhg-game/new_active.png"),
    name: "最新"
  },
  4: {
    icon: require("../../../assets/img/game/new-game/arcade.png"),
    name: "街机"
  },
  5: {
    icon: require("../../../assets/img/game/new-game/fishing.png"),
    name: "捕鱼"
  },
  6: {
    icon: require("../../../assets/img/game/new-game/niuniu.png"),
    name: "牛牛"
  },
  7: {
    icon: require("../../../assets/img/game/new-game/hundred.png"),
    name: "百人"
  },
  8: {
    icon: require("../../../assets/img/game/new-game/scriptures.png"),
    name: "经典"
  },
  9: {
    icon: require("../../../assets/img/game/new-game/my-love.png"),
    name: "最爱"
  },
  97: {
    icon: require("../../../assets/img/game/amhg-game/all-game-fish.png"),
    icon_active: require("../../../assets/img/game/amhg-game/all-game-fish_active.png"),
    name: "全部"
  },
  98: {
    icon: require("../../../assets/img/game/amhg-game/all_game_chess.png"),
    icon_active: require("../../../assets/img/game/amhg-game/all-game-chess_active.png"),
    name: "全部"
  },
  99: {
    icon: require("../../../assets/img/game/amhg-game/all_game.png"),
    icon_active: require("../../../assets/img/game/amhg-game/all_game_active.png"),
    name: "全部"
  },
  10005: {
    icon: require("../../../assets/img/game/amhg-game/BG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/BG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/BG-error-icon.png"),
    name: "BG",
    AfirmIcon: require("../../../assets/img/game/new-game/BG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-BG-firm.png"),
  },
  10014: {
    icon: require("../../../assets/img/game/new-game/AE.png"),
    errorIcon: require("../../../assets/img/game/new-game/AE-error-icon.png"),
    name: "AE",
    AfirmIcon: require("../../../assets/img/game/new-game/AE-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-AE-firm.png"),
  },
  10015: {
    icon: require("../../../assets/img/game/amhg-game/AG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/AG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/AG-error-icon.png"),
    name: "AG",
    AfirmIcon: require("../../../assets/img/game/new-game/AG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-AG-firm.png"),
  },
  10016: {
    icon: require("../../../assets/img/game/amhg-game/BBIN.png"),
    icon_active: require("../../../assets/img/game/amhg-game/BBIN_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/BBIN-error-icon.png"),
    name: "BBIN",
    AfirmIcon: require("../../../assets/img/game/new-game/BBIN-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-BBIN-firm.png"),
  },
  10018: {
    icon: require("../../../assets/img/game/amhg-game/CQ9.png"),
    icon_active: require("../../../assets/img/game/amhg-game/CQ9_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/CQ9-error-icon.png"),
    name: "CQ9",
    AfirmIcon: require("../../../assets/img/game/new-game/CQ9-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-CQ9-firm.png"),
  },
  10019: {
    icon: require("../../../assets/img/game/amhg-game/DT.png"),
    icon_active: require("../../../assets/img/game/amhg-game/DT_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/DT-error-icon.png"),
    name: "DT",
    AfirmIcon: require("../../../assets/img/game/new-game/DT-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-DT-firm.png"),
  },
  10020: {
    icon: require("../../../assets/img/game/amhg-game/FG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/FG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/FG-error-icon.png"),
    name: "FG",
    AfirmIcon: require("../../../assets/img/game/new-game/FG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-FG-firm.png"),
  },
  10021: {
    icon: require("../../../assets/img/game/amhg-game/JDB.png"),
    icon_active: require("../../../assets/img/game/amhg-game/JDB_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/JDB-error-icon.png"),
    name: "JDB",
    AfirmIcon: require("../../../assets/img/game/new-game/JDB-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-JDB-firm.png"),
  },
  10022: {
    icon: require("../../../assets/img/game/amhg-game/MG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/MG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/MG-error-icon.png"),
    name: "MG",
    AfirmIcon: require("../../../assets/img/game/new-game/MG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-MG-firm.png"),
  },
  10023: {
    icon: require("../../../assets/img/game/amhg-game/MW.png"),
    icon_active: require("../../../assets/img/game/amhg-game/MW_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/MW-error-icon.png"),
    name: "MW",
    AfirmIcon: require("../../../assets/img/game/new-game/MW-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-MW-firm.png"),
  },
  10024: {
    icon: require("../../../assets/img/game/amhg-game/PT.png"),
    icon_active: require("../../../assets/img/game/amhg-game/PT_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/PT-error-icon.png"),
    name: "PT",
    AfirmIcon: require("../../../assets/img/game/new-game/PT-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-PT-firm.png"),
  },
  10025: {
    icon: require("../../../assets/img/game/new-game/TTG.png"),
    errorIcon: require("../../../assets/img/game/new-game/TTG-error-icon.png"),
    name: "TTG",
    AfirmIcon: require("../../../assets/img/game/new-game/TTG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-TTG-firm.png"),
  },
  11320: {
    icon: require("../../../assets/img/game/amhg-game/PG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/PG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/PG-error-icon.png"),
    name: "PG",
    AfirmIcon: require("../../../assets/img/game/new-game/PG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-PG-firm.png"),
  },
  10041: {
    icon: require("../../../assets/img/game/amhg-game/VG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/VG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/VG-error-icon.png"),
    name: "VG",
    AfirmIcon: require("../../../assets/img/game/new-game/VG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-VG-firm.png"),
  },
  10694: {
    icon: require("../../../assets/img/game/amhg-game/TY.png"),
    icon_active: require("../../../assets/img/game/amhg-game/TY_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/TH-error-icon.png"),
    name: "天游",
    AfirmIcon: require("../../../assets/img/game/new-game/TH-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-TH-firm.png"),
  },
  10612: {
    icon: require("../../../assets/img/game/amhg-game/LEG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/LEG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/LEG-error-icon.png"),
    name: "乐游",
    AfirmIcon: require("../../../assets/img/game/new-game/LEG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-LEG-firm.png"),
  },
  10042: {
    icon: require("../../../assets/img/game/amhg-game/KY.png"),
    icon_active: require("../../../assets/img/game/amhg-game/KY_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/KY-error-icon.png"),
    name: "开元",
    AfirmIcon: require("../../../assets/img/game/new-game/KY-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-KY-firm.png"),
  },
  10732: {
    icon: require("../../../assets/img/game/amhg-game/FG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/FG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/FG-error-icon.png"),
    name: "FG",
    AfirmIcon: require("../../../assets/img/game/new-game/FG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-FG-firm.png"),
  },
  10636: {
    icon: require("../../../assets/img/game/new-game/chess-DZ.png"),
    errorIcon: require("../../../assets/img/game/new-game/DZ-error-icon.png"),
    name: "大战",
    AfirmIcon: require("../../../assets/img/game/new-game/DZ-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-DZ-firm.png"),
  },
  10055: {
    icon: require("../../../assets/img/game/amhg-game/AG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/AG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/AG-error-icon.png"),
    name: "AG",
    AfirmIcon: require("../../../assets/img/game/new-game/AG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-AG-firm.png"),
  },
  10054: {
    icon: require("../../../assets/img/game/amhg-game/JDB.png"),
    icon_active: require("../../../assets/img/game/amhg-game/JDB_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/JDB-error-icon.png"),
    name: "JDB",
    AfirmIcon: require("../../../assets/img/game/new-game/JDB-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-JDB-firm.png"),
  },
  10056: {
    icon: require("../../../assets/img/game/amhg-game/FG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/FG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/FG-error-icon.png"),
    name: "FG",
    AfirmIcon: require("../../../assets/img/game/new-game/FG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-FG-firm.png"),
  },
  10057: {
    icon: require("../../../assets/img/game/amhg-game/CQ9.png"),
    icon_active: require("../../../assets/img/game/amhg-game/CQ9_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/CQ9-error-icon.png"),
    name: "CQ9",
    AfirmIcon: require("../../../assets/img/game/new-game/CQ9-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-CQ9-firm.png"),
  },
  10053: {
    icon: require("../../../assets/img/game/amhg-game/MW.png"),
    icon_active: require("../../../assets/img/game/amhg-game/MW_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/MW-error-icon.png"),
    name: "MW",
    AfirmIcon: require("../../../assets/img/game/new-game/MW-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-MW-firm.png"),
  },
  10058: {
    icon: require("../../../assets/img/game/amhg-game/BG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/BG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/BG-error-icon.png"),
    name: "BG",
    AfirmIcon: require("../../../assets/img/game/new-game/BG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-BG-firm.png"),
  },
  11440: {
    icon: require("../../../assets/img/game/amhg-game/BBIN.png"),
    icon_active: require("../../../assets/img/game/amhg-game/BBIN_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/BBIN-error-icon.png"),
    name: "BBIN",
    AfirmIcon: require("../../../assets/img/game/new-game/BBIN-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-BBIN-firm.png"),
  },
  11660: {
    icon: require("../../../assets/img/game/amhg-game/TY.png"),
    icon_active: require("../../../assets/img/game/amhg-game/TY_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/TH-error-icon.png"),
    name: "天游",
    AfirmIcon: require("../../../assets/img/game/new-game/TH-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-TH-firm.png"),
  },
  11677: {
    icon: require("../../../assets/img/game/amhg-game/PT.png"),
    icon_active: require("../../../assets/img/game/amhg-game/PT_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/PT-error-icon.png"),
    name: "PT",
    AfirmIcon: require("../../../assets/img/game/new-game/PT-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-PT-firm.png"),
  },
  11659: {
    icon: require("../../../assets/img/game/amhg-game/KY.png"),
    icon_active: require("../../../assets/img/game/amhg-game/KY_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/KY-error-icon.png"),
    name: "开元",
    AfirmIcon: require("../../../assets/img/game/new-game/KY-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-KY-firm.png"),
  },
  11661: {
    icon: require("../../../assets/img/game/amhg-game/LEG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/LEG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/LEG-error-icon.png"),
    name: "乐游",
    AfirmIcon: require("../../../assets/img/game/new-game/LEG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-LEG-firm.png"),
  },
  11662: {
    icon: require("../../../assets/img/game/amhg-game/VG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/VG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/VG-error-icon.png"),
    name: "VG",
    AfirmIcon: require("../../../assets/img/game/new-game/VG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-VG-firm.png"),
  },
  11746: {
    icon: require("../../../assets/img/game/amhg-game/MG.png"),
    icon_active: require("../../../assets/img/game/amhg-game/MG_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/MG-error-icon.png"),
    name: "MG",
    AfirmIcon: require("../../../assets/img/game/new-game/MG-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-MG-firm.png"),
  },
  11906: {
    icon: require("../../../assets/img/game/amhg-game/PP.png"),
    icon_active: require("../../../assets/img/game/amhg-game/PP_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/PP-error-icon.png"),
    name: "PP",
    AfirmIcon: require("../../../assets/img/game/new-game/PP-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-PP-firm.png"),
  },
  11828: {
    icon: require("../../../assets/img/game/amhg-game/KX_qp.png"),
    icon_active: require("../../../assets/img/game/amhg-game/KX_qp_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/fish-KX-error-icon.png"),
    name: "凯旋",
    AfirmIcon: require("../../../assets/img/game/new-game/KX-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-KX-firm.png"),
  },
  11857: {
    icon: require("../../../assets/img/game/amhg-game/XSJ.png"),
    icon_active: require("../../../assets/img/game/amhg-game/XSJ_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/XSJ-error-icon.png"),
    name: "新世界",
    AfirmIcon: require("../../../assets/img/game/new-game/XSJ-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-XSJ-firm.png"),
  },
  11775: {
    icon: require("../../../assets/img/game/amhg-game/fish-MT.png"),
    icon_active: require("../../../assets/img/game/amhg-game/fish-MT_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/fish-MT-error-icon.png"),
    name: "MT",
    AfirmIcon: require("../../../assets/img/game/new-game/MT-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-MT-firm.png"),
  },
  11881: {
    icon: require("../../../assets/img/game/amhg-game/chess-Ak.png"),
    icon_active: require("../../../assets/img/game/amhg-game/chess-Ak-active.png"),
    errorIcon: require("../../../assets/img/game/new-game/AK-error-icon.png"),
    name: "AK",
    AfirmIcon: require("../../../assets/img/game/new-game/AK-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-AK-firm.png"),
  },
  11759: {
    icon: require("../../../assets/img/game/amhg-game/chess-DFW.png"),
    icon_active: require("../../../assets/img/game/amhg-game/chess-DFW_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/DFW-error-icon.png"),
    name: "大富翁",
    AfirmIcon: require("../../../assets/img/game/new-game/DFW-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-DFW-firm.png"),
  },
  12036: {
    icon: require("../../../assets/img/game/amhg-game/fish-MT.png"),
    icon_active: require("../../../assets/img/game/amhg-game/fish-MT_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/fish-MT-error-icon.png"),
    name: "MT",
    AfirmIcon: require("../../../assets/img/game/new-game/MT-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-MT-firm.png"),
  },
  12042: {
    icon: require("../../../assets/img/game/amhg-game/KX_py.png"),
    icon_active: require("../../../assets/img/game/amhg-game/KX_py_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/fish-KX-error-icon.png"),
    name: "凯旋",
    AfirmIcon: require("../../../assets/img/game/new-game/KX-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-KX-firm.png"),
  },
  12465: {
    icon: require("../../../assets/img/game/amhg-game/chess-MB.png"),
    icon_active: require("../../../assets/img/game/amhg-game/chess-MB_active.png"),
    errorIcon: require("../../../assets/img/game/new-game/chess-MB-error-icon.png"),
    name: "美博",
    AfirmIcon: require("../../../assets/img/game/new-game/MB-firm.png"),
    BfirmIcon: require("../../../assets/img/game/new-game/B-MB-firm.png"),
  }
}